[package]
name = "fm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18"
open = "3.0"

[profile.release]
lto=true
strip="debuginfo"
